schemaVersion: 2.2.0
metadata:
  name: sample-using-parent-fgfg-gfdgd-gdgfdf-gdgdgf-gdgd
parent:
  uri: https://raw.githubusercontent.com/testsfactory/parentDevfile/main/parent.yaml
  components:
    - name: tools
      container:
        env:
          - name: DEVFILE_ENV_VAR
            value: 'true'
commands:
  - id: devfile-command
    exec:
      label: '1. This command from the devfile'
      component: tools
      commandLine: echo "Hello from devfile"
